apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flask-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "flask-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "flask-chart.name" . }}
    spec:
      containers:
      - name: flask-app
        image: ghcr.io/aldentaye/python-mq-demo:main
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: ghcrpull
