apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-chart.fullname" . }}-flask-service
spec:
  selector:
    app: {{ include "flask-chart.name" . }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000