apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-chart.fullname" . }}-grafana-service
spec:
  selector:
    app: {{ include "flask-chart.name" . }}-grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
