apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
data: 
  prometheus.yml: |
    global:
        scrape_interval: 15s
        
    scrape_configs:
      - job_name: 'nginx'
        static_configs:
          - targets: ['{{ include "flask-chart.fullname" . }}-nginx-service:80']

