apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flask-chart.fullname" . }}-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "flask-chart.name" . }}-prometheus
  template:
    metadata:
      labels:
        app: {{ include "flask-chart.name" . }}-prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
          ports:
            - containerPort: 9090
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-configmap
            items:
              - key: prometheus.yml
                path: prometheus.yml

