apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-chart.fullname" . }}-prometheus-service
spec:
  selector:
    app: {{ include "flask-chart.name" . }}-prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
