apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-chart.fullname" . }}-rabbitmq
spec:
  selector:
    app: {{ include "flask-chart.name" . }}-rabbitmq
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 5672
      name: amqp
    - protocol: TCP
      port: {{ .Values.service.managementPort }}
      targetPort: 15672
      name: management
