apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "flask-chart.fullname" . }}-rabbitmq
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "flask-chart.fullname" . }}-rabbitmq-headless
  selector:
    matchLabels:
      app: {{ include "flask-chart.name" . }}-rabbitmq
  template:
    metadata:
      labels:
        app: {{ include "flask-chart.name" . }}-rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: "{{ .Values.rabbitmq.image.repository }}:{{ .Values.rabbitmq.image.tag }}"
        ports:
        - containerPort: 5672
          name: amqp
        - containerPort: 15672
          name: management

