# Default values for ..
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

flask:
  image:
    repository: ghcr.io/aldentaye/python-mq-demo:main
    tag: v1
    
registrySecretName: ghcrpull

rabbitmq:
  image:
    repository: "rabbitmq"
    tag: "3-management"
    pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 5672
  managementPort: 15672
