# Default values for ..
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

flask:
  image:
    repository: your-registry/flask-app
    tag: v1

rabbitmq:
  username: guest
  password: guest


